### ISSUE TITLE
Reconnecting with same rerun id

### ISSUE THREAD

**Issue by lucasw** [rerun-io/rerun#11585]
**Describe the bug**

When I reconnect to rerun using the same name and rerun_id as previously used rerun becomes laggy and unresponsive, and I have to restart it to recover.  Using a fresh id works fine and as expected.

The play button is also behaving wrong, I can jump back in the timeline, press play, and then it fast forwards to the end instead of playing at a 1.0 rate.

**To Reproduce**

```
    let mut rec = rerun::RecordingStreamBuilder::new(rerun::ApplicationId::from(rerun_name.clone()));
    if let Some(rerun_id) = rerun_id {
        println!("using rerun id '{rerun_id}'");
        rec = rec.recording_id(rerun_id.to_string());
    }
    let rec = rec.spawn()?;
```

Every 1.0/60.0 seconds I'm updating the rerun time with current system time represented as an f64:

```
rec.set_timestamp_secs_since_epoch("view", t_seconds);
```
And then doing a bunch of rerun logs.

I thought I was confusing rerun by giving it a timestamp that was earlier in time than the end of the previous run, doubling up data every update, but even then the laggy behavior doesn't make sense, I would expect rerun to be robust against it and worst case is that the position of objects flickers between the old run and new run.

**Expected behavior**

I'd expect every time I reconnect using the same name and recording id that there would be a gap in the timeline for however long I was disconnected, and then the new telemetry would show up and play normally.

**Desktop (please complete the following information):**
 Linux Ubuntu 24.04

**Rerun version**

```
rerun-cli 0.26.0 (base map_view nasm native_viewer oss_server release_full release_no_web_viewer web_viewer) [rustc 1.88.0 (6b00bc388 2025-06-23), LLVM 20.1.5] x86_64-unknown-linux-gnu 11526/merge 831c187, built 2025-10-16T13:29:59.401210833Z
Video features: av1 default ffmpeg nasm serde
```

**Additional context**

**Comment by lucasw** [comment]
I'm trying to create a reproducible example, but so far the example works fine (except for the play button jumping to the end of the timeline): https://github.com/lucasw/jolt_rust_cpp/tree/main/jolt_rerun

**Comment by lucasw** [comment]
https://www.youtube.com/watch?v=pJTzN9-Kia0 shows it near the end (though the rerun UI remains responsive, it's just the playback that falters)- and I'm noticing for the first time the `Latency` pop up on the top of the rerun window- it jumps up at 2:05 but recovers, then gets really bad when I restart the client.

Also the play button works as expected at 1:09, but only for playing from the start, everytime else it skips to the end.  Now when I experiment the play button does appear to work as expected but only after hitting 'loop to start', and then it continues to work even after disabling loop to start again- is that intended behavior?

**Comment by grtlr** [comment]
Thank you for reporting—that looks really bad.

Could you please provide a screenshot of the latency panel that opens when hovering over the latency measure in the top bar?

The panels shows the different "hops" that the data takes and should give us more context to see where Rerun spends too much time.

**Comment by lucasw** [comment]
<img width="1169" height="1368" alt="Image" src="https://github.com/user-attachments/assets/260872ac-3747-4d5e-beae-bcdea5c93c79" />

Should I try out installing the profiler next?

**Comment by grtlr** [comment]
Oh wow, thank you!<br><br>Yeah, since this seems to be on the viewer side the profiler might give more information. You should be able to run it with:

```
rerun --profile
```

**Comment by lucasw** [comment]
<img width="3625" height="2046" alt="Image" src="https://github.com/user-attachments/assets/0ee88acd-104e-4ceb-aa32-c33096ecc081" />

**Comment by lucasw** [comment]
Actually I was able to duplicate this with https://github.com/lucasw/jolt_rust_cpp/tree/main/jolt_rerun, though it took a couple more reconnects.  I'll see if it is the same on another computer as well.

**Comment by lucasw** [comment]
This is after recycling `jolt_rerun` about five times:
<img width="3685" height="2042" alt="Image" src="https://github.com/user-attachments/assets/828d060f-4a8b-4a1d-951a-d40b2895e519" />

**Comment by grtlr** [comment]
Thank you, that repro will help a lot!<br><br>I will start to look into this soon, we have done some recent changes to the transform cache that shows up in the profile.

**Comment by Wumpf** [comment]
> When I reconnect to rerun using the same name and rerun_id as previously used rerun becomes laggy and unresponsive, and I have to restart it to recover. Using a fresh id works fine and as expected.
> The play button is also behaving wrong, I can jump back in the timeline, press play, and then it fast forwards to the end instead of playing at a 1.0 rate.

To clarify, are both issues new in 0.26? I suspect that transform processing was already bad in the describe scenario before but maybe something made it worse.
I believe the underlying issue is that the `TransformResolutionCache` invalidates & recomputes all previously computed transforms forward in time every time something is logged in the past - if it's that then we already had the problem, but changes in that area might have made it worse / more noticeable (and generally it's a problem we need to do something about :/)

The play button behavior is almost certainly a separate issue. On the last release some things moved to blueprint, so maybe something got messed up there (or maybe in https://github.com/rerun-io/rerun/pull/11340 since it adds a concept of invalid time ranges that get jumped over, might be that those aren't correctly updated 🤔). Tbh can't quite make sense yet of what you're describing, sounds messy either way. I wouldn't surprised it to go back to track latest every time you connect again, but play/pause/scrub should not be affected and just work and not just randomly skip to the end 😬 

Again, thanks for all the information provided so far, def. want to look into those timely! :)

**Comment by lucasw** [comment]
I think something similar with the latency was happening in 0.24.1 but I didn't stop to investigate thoroughly until now with 0.26.   Before that I hadn't tried setting the id because I've only had one application logging, but here I moved to two and wanted to see all their visuals commingled together.

The play button may have been working fine earlier though.

**Comment by Wumpf** [comment]
@lucasw we got a fix landed for the playbutton issue and here's a fix for the performance problem

* https://github.com/rerun-io/rerun/pull/11655

I think that should fix the massive slowdown you've experienced and make the scenario usable! Would be awesome if you could try it out, I mostly worked with a purpose built repro case.

That said, I do want to highlight that Rerun isn't _great_ with overwriting existing data the way you do. Any particular reason you don't just create a new recording with the same application?

**Comment by lucasw** [comment]
> That said, I do want to highlight that Rerun isn't great with overwriting existing data the way you do.

Is it my log_statics that are the issue?  I do dump a bunch of line strips and a big Mesh3D at the start of the application, but everything after that is regular logs using the timestamp set like this

```
        let t_now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("SystemTime since UNIX_EPOCH!")
            .as_secs_f64();
        rec.set_timestamp_secs_since_epoch("view", t_now);
...
            rec.log(
                "world/ray_cast_results",
                &rerun::Points3D::new(points).with_radii(radii),
            )?;
```

I don't think I'm overwriting anything at the same timestamp except for those log statics at the start, though I've commented out the two large ones and am still seeing the latency climb upon reconnection (using .  My assumption was that log static is more efficient because there's no time lookup on the (using 22a728747ef2cbfb8990a3ce620fd044e5a5f592 which has a55361910681c7ade5a4cec0f29cea92f5d82a39 in history) other side (or do two sequential log_statics still get timestamped at the moment the second one arrives, instead of rewriting history if the new one is different?)

> Any particular reason you don't just create a new recording with the same application?

What's an ergonomic alternative where I can have multiple processes commingling data in the same rerun view where I don't have to copy paste rerun_ids- just a shell script that generates a new random rerun id and provides it to both, and I have to restart both processes every iteration?  That's not terrible for what I'm doing right now I suppose, but seems limiting.

The other approach is to concentrate all rerun logging into a single process, and have other processes report to it via IPC of my choosing (ros1 right now), and I would just restart that rerun process if I wanted a new recording.  Or I could re-use some of the existing rerun api, applications would still do rerun log but would be communicating with a custom rerun relay process which would then control a regular rerun viewer?

Basically I'd really like `rviz` with a memory limited rolling buffer and I could just leave it running for hours if necessary and by default everything logs into one recording.  Even better would be if I could recycle it and have every client automatically reconnect, and the time history would be empty but log_statics would somehow pop back in- maybe the relay is the solution there as well.  (I am in the process of moving towards fewer more monolithic processes instead of dozens of ros nodes, so maybe I can get used to rerun as-is though)

**Comment by Wumpf** [comment]
Maybe I misunderstood what's happening here - using a fixed recording id is indeed the way how working with multiple processes is meant to work. And the way you use log static is fine as well. In fact overwriting log static after the fact works quite well, unlike with timed data it will discard any previous data on arrival for static components. So keep doing all that 😄 
What _is_ potentially problematic is overwriting the same components at a timestamp you previously already had data about it. Rerun will keep the previous result side by side with the old and assume that the old comes just before the new data. That can create quite a bit of overhead since the underlying chunks have to be "zipped up" on the fly.
It should of course still work just fine and not be performing as poorly as demonstrated.

On that note, did you have the chance to try out the fixes? The play button fix arrived in [0.26.2](https://github.com/rerun-io/rerun/releases/tag/0.26.2), the perf improvement was unfortunately to invasive to put it into a patch release, so that's only available on the [nightly](https://github.com/rerun-io/rerun/releases/tag/prerelease)
Would be awesome if you could give it a spin and check whether stuff actually improved for you.


> Basically I'd really like rviz with a memory limited rolling buffer and I could just leave it running for hours if necessary and by default everything logs into one recording

The memory limited should pretty much have that effect.

> Even better would be if I could recycle it and have every client automatically reconnect, and the time history would be empty but log_statics would somehow pop back in- maybe the relay is the solution there as well.

Blueprints can fullfill part of that 🤔. We can't hold "new" entities in there yet that didn't show up in the recording, but via overrides you can actually have arbitrary data inside the blueprint and then share that across many recordings.

**Comment by lucasw** [comment]
The play button does work as expected now.

I built from source with 703c1fdee2a962a3115dfaaf22b499837df513a5 using this:

```
RERUN_DISABLE_WEB_VIEWER_SERVER=true cargo install rerun-cli --path crates/top/rerun-cli/ --locked
```

```
rerun-cli 0.27.0-alpha.1+dev 
x86_64-unknown-linux-gnu
rerun-cli features: base default map_view native_viewer oss_server web_viewer
rustc 1.88.0 (6b00bc388 2025-06-23), LLVM 20.1.5
```

Now I can reconnect and no latency issues- thanks!  But I'm still not seeing where in [my code](https://github.com/lucasw/jolt_rust_cpp/blob/main/jolt_rerun/src/main.rs#L121-L226) I was overwriting at the same timestamp.

Blueprints sound useful but I haven't learned how to use them yet- I can figure it out but more examples (ideally in rust) and pictures and videos would help, understandable if that takes a while.
